name: Build On EC2

env:
  DOCKER_CONTAINER_NAME: laughing_kare

on:
    push:
        branches:
            - main

jobs:
  MY-CI-CD-JOBS:
    runs-on: self-hosted
    steps:
      - name: test if it works
        run: echo "yaho it works"

      - name: print runner info
        run: |
          pwd 
          echo $USER 

      - name: print env var
        run: echo ${{env.DOCKER_CONTAINER_NAME}}
