name: Build On EC2

env:
  DOCKER_CONTAINER_NAME: laughing_kare

on:
    push:
        branches:
            - main

jobs:
  warmup:
    runs-on: self-hosted
    steps:
      - name: test if it works
        run: echo "yaho it works"

      - name: print runner info
        run: |
          pwd 
          echo $USER 

      - name: print env var
        run: echo ${{env.DOCKER_CONTAINER_NAME}}

      - name: print names of running containsers
        run: docker ps --format \{\{.Names\}\}

  setup-docker-container:
    runs-on: self-hosted
    needs: warmup
    steps:
      - name: git clone
        uses: actions/checkout@v5

      - name: npm install then build
        run: |
          npm install
          npm run build

      - name: build docker image
        run: docker build --tag deploy-demo:latest --platform linux/amd64 .

      - name: stop and remove existing container
        run: |
          docker stop ${{env.DOCKER_CONTAINER_NAME}} || true
          docker rm ${{env.DOCKER_CONTAINER_NAME}} || true

      - name: create container by run
        run: docker run --detach --publish 5173:80 --name ${{env.DOCKER_CONTAINER_NAME}} deploy-demo:latest

